"""A reminder call delivers one reminder and nothing else.

A due reminder whose owner asked to be called about it is an isolated job: the
dispatcher hands the worker one opaque reminder id of one owner, and the
answered leg exists to say those words and then talk normally. Two things made
that leg say more than that:

* the opening line was generated by the model from an instruction prompt, and
  the system prompt carries a generic reminder example, so the model could open
  with invented or echoed example content before the real reminder;
* the leg was still wired with the background-task bridge and callback arming,
  so fixed background/callback lines (including the nothing-is-running reply)
  were reachable on a call that has no background task at all.

The rules held to below: an isolated reminder call speaks one fixed greeting
that names nothing, then exactly the one trusted reminder it was placed for; it
never reaches the LLM for that opening; it gets no background bridge, no
callback arming and no ledger continuation. Callback calls, hand-offs and
ordinary sessions are untouched, and every path still waits for a human.
"""

from __future__ import annotations

import importlib.util
import json
import sqlite3
from pathlib import Path
from types import SimpleNamespace

import pytest

from caal.outbound_runtime import OutboundRoomConfig
from caal.tools import alarms_tools, reminder_delivery, reminders_tools

APPROVED = "+17805558345"
ANA = "usr_" + "a" * 24
NOW = 1_000_000
SOON = "PT30M"
# Two harmless stand-in titles. Only one of them is ever the reminder of a call.
SELECTED_TITLE = "water the office plant"
OTHER_TITLE = "swap the desk lamp bulb"
TASK_ID = "bt_" + "0" * 16

_voice_agent = None


def _load_voice_agent():
    global _voice_agent
    if _voice_agent is None:
        module_path = Path(__file__).parents[1] / "voice_agent.py"
        spec = importlib.util.spec_from_file_location("voice_agent_reminder_call_test", module_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _voice_agent = module
    return _voice_agent


class _FakeSession:
    """Records exactly what a session was asked to speak, and how."""

    def __init__(self) -> None:
        self.said: list[str] = []
        self.generated: list[str] = []

    async def say(self, text: str, **kwargs) -> None:
        self.said.append(text)

    async def generate_reply(self, *, instructions: str) -> None:
        self.generated.append(instructions)
        self.said.append("<model reply to: " + instructions + ">")


async def _noop() -> None:
    return None


@pytest.fixture
def store(monkeypatch, tmp_path):
    path = tmp_path / "assistant.sqlite3"
    monkeypatch.setattr(alarms_tools, "STORE_PATH", path)
    monkeypatch.setattr(reminders_tools, "STORE_PATH", path)
    monkeypatch.setattr(reminder_delivery, "STORE_PATH", path)
    return path


def _reminder_id(path, title: str, user_id: str = ANA) -> str:
    connection = sqlite3.connect(path)
    try:
        rows = connection.execute(
            "SELECT id FROM reminders WHERE user_id = ? AND title = ?", (user_id, title)
        ).fetchall()
    finally:
        connection.close()
    assert len(rows) == 1
    return rows[0][0]


@pytest.fixture
def two_reminders(store):
    """Two reminders of one owner; the call is placed for exactly one of them."""
    for title in (SELECTED_TITLE, OTHER_TITLE):
        reminders_tools.create_reminder(title=title, due=SOON, user_id=ANA, now=NOW)
    return (_reminder_id(store, SELECTED_TITLE), _reminder_id(store, OTHER_TITLE))


def _config(**extra) -> OutboundRoomConfig:
    metadata = dict(caal_outbound=True, attempt_id="abc", destination=APPROVED)
    metadata.update(extra)
    config = OutboundRoomConfig.from_dispatch_metadata(
        json.dumps(metadata),
        allowed_destinations=APPROVED,
        resolve_user_destination=lambda user_id: APPROVED,
    )
    assert config is not None
    return config


# --- the call-kind predicate -------------------------------------------------------------


def test_only_an_isolated_reminder_job_is_kept_from_the_llm_and_the_background(
    two_reminders,
) -> None:
    from caal.outbound_runtime import uses_background_session, uses_llm_greeting

    selected, _other = two_reminders
    reminder = _config(reminder_id=selected)
    callback = _config(callback_task_id=TASK_ID)
    ordinary = _config()

    assert reminder.is_isolated_reminder is True
    assert callback.is_isolated_reminder is False
    assert ordinary.is_isolated_reminder is False

    assert uses_llm_greeting(reminder) is False
    assert uses_background_session(reminder) is False
    for other in (callback, ordinary, None):
        assert uses_llm_greeting(other) is True
        assert uses_background_session(other) is True


def test_a_callback_that_also_carries_a_reminder_id_is_a_callback(two_reminders) -> None:
    """Precedence is intentional: a settled task still owes its outcome."""
    selected, _other = two_reminders
    both = _config(reminder_id=selected, callback_task_id=TASK_ID)
    assert both.is_callback is True
    assert both.is_isolated_reminder is False


def test_the_kind_of_a_call_is_never_taken_from_the_caller(two_reminders) -> None:
    """Only the validated ids decide; dispatch metadata cannot assert a kind."""
    from caal.outbound_runtime import uses_llm_greeting

    selected, _other = two_reminders
    lying = _config(reminder_id=selected, is_reminder=False, use_llm_greeting=True)
    assert lying.is_isolated_reminder is True
    assert uses_llm_greeting(lying) is False


# --- the opening of a reminder call ------------------------------------------------------


@pytest.mark.asyncio
async def test_a_reminder_call_speaks_a_fixed_greeting_then_only_its_own_reminder(
    two_reminders,
) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders
    session = _FakeSession()

    await voice_agent.deliver_outbound_opening(session, _config(reminder_id=selected, user_id=ANA))

    assert session.generated == []
    assert session.said == [
        voice_agent.REMINDER_CALL_GREETING,
        reminder_delivery.reminder_message(SELECTED_TITLE),
    ]
    spoken = " ".join(session.said).lower()
    assert OTHER_TITLE not in spoken
    assert SELECTED_TITLE not in voice_agent.REMINDER_CALL_GREETING.lower()


def test_the_fixed_greeting_names_nothing_of_the_user_or_the_prompt() -> None:
    voice_agent = _load_voice_agent()
    greeting = voice_agent.REMINDER_CALL_GREETING
    assert isinstance(greeting, str) and greeting.strip()
    lowered = greeting.lower()
    for leaked in ("example", "task", "background", "%s"):
        assert leaked not in lowered


@pytest.mark.asyncio
async def test_a_reminder_that_cannot_be_read_is_not_replaced_by_the_model(
    two_reminders,
) -> None:
    """A missing row means the greeting and silence, never an invented reminder."""
    voice_agent = _load_voice_agent()
    missing = "0" * 8 + "-" + "0" * 4 + "-" + "0" * 4 + "-" + "0" * 4 + "-" + "0" * 12
    session = _FakeSession()

    await voice_agent.deliver_outbound_opening(session, _config(reminder_id=missing, user_id=ANA))

    assert session.generated == []
    assert session.said == [voice_agent.REMINDER_CALL_GREETING]


@pytest.mark.asyncio
async def test_a_callback_call_still_gets_its_generated_greeting_and_outcome(monkeypatch) -> None:
    voice_agent = _load_voice_agent()
    monkeypatch.setattr(
        voice_agent, "callback_outcome_message", lambda task_id: "The task you asked about is done."
    )
    session = _FakeSession()

    await voice_agent.deliver_outbound_opening(session, _config(callback_task_id=TASK_ID))

    assert session.generated == [voice_agent.CALLBACK_GREETING_INSTRUCTIONS]
    assert session.said[-1] == "The task you asked about is done."


@pytest.mark.asyncio
async def test_an_ordinary_session_still_opens_with_the_generated_greeting() -> None:
    voice_agent = _load_voice_agent()
    session = _FakeSession()

    await voice_agent.deliver_outbound_opening(session, None)

    assert session.generated == [voice_agent.DEFAULT_GREETING_INSTRUCTIONS]


# --- no background or callback surface on a reminder call ---------------------------------


def _runtime() -> dict:
    return dict(
        background_tasks_enabled=True,
        background_task_max_concurrency=1,
        background_task_timeout_seconds=1.0,
        work_router_enabled=False,
        telegram_bot_token="",
        telegram_chat_id="",
    )


def test_a_reminder_call_is_given_no_background_task_bridge(two_reminders) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders

    assert (
        voice_agent.build_background_task_bridge(
            _runtime(),
            provider=SimpleNamespace(),
            session_key="caal-outbound-abc",
            outbound_config=_config(reminder_id=selected),
        )
        is None
    )
    assert (
        voice_agent.build_background_task_bridge(
            _runtime(),
            provider=SimpleNamespace(),
            session_key="caal-outbound-abc",
            outbound_config=_config(callback_task_id=TASK_ID),
        )
        is not None
    )


def test_a_reminder_call_can_arm_no_callback(two_reminders) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders
    metadata = json.dumps(dict(caal_outbound=True, attempt_id="abc", destination=APPROVED))
    ctx = SimpleNamespace(
        job=SimpleNamespace(metadata=metadata),
        api=SimpleNamespace(room=object()),
        room=SimpleNamespace(name="caal-outbound-abc"),
    )
    config = _config(reminder_id=selected)

    assert (
        voice_agent.build_callback_arming(
            ctx, session=_FakeSession(), bridge=None, outbound_config=lambda: config
        )
        is None
    )


@pytest.mark.asyncio
async def test_a_reminder_call_turn_reaches_no_background_or_callback_reply() -> None:
    """With no bridge and no arming, the fixed background replies are unreachable."""
    voice_agent = _load_voice_agent()
    handler = voice_agent.LocalTurnHandler(
        phone_handoff=None,
        session=_FakeSession(),
        end_call=_noop,
        background=None,
        arm_callback_and_end_call=None,
    )
    assert handler._callback_available() is False
    consumed = await handler._handle_local_commands("hang up and call me back when you are done")
    assert consumed is False


@pytest.mark.asyncio
async def test_a_reminder_call_hydrates_no_ledger_continuation(monkeypatch, two_reminders) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders
    conversation_id = "conv_" + "1" * 24
    claimed: list[str] = []
    released: list[str] = []
    monkeypatch.setattr(
        voice_agent.conversation_ledger,
        "claim_continuation",
        lambda cid, **kwargs: claimed.append(cid),
    )
    monkeypatch.setattr(
        voice_agent.conversation_ledger,
        "release_continuation",
        lambda cid, **kwargs: released.append(cid),
    )
    config = _config(reminder_id=selected, conversation_id=conversation_id)

    await voice_agent._hydrate_answered_call(config, agent=None, recorder=None, background=None)

    assert claimed == []
    assert released == [conversation_id]


# --- the human gate is unchanged ----------------------------------------------------------


class _FakeAMDFactory:
    def __init__(self, category: str) -> None:
        self.category = category

    def __call__(self, session, **kwargs):
        factory = self

        class _Detector:
            async def __aenter__(self):
                return self

            async def __aexit__(self, *exc):
                return False

            async def execute(self):
                return SimpleNamespace(category=SimpleNamespace(value=factory.category))

        return _Detector()


class _FakeContext:
    def __init__(self) -> None:
        self.api = SimpleNamespace(sip=SimpleNamespace(create_sip_participant=self._create))
        self.room = SimpleNamespace(name="caal-outbound-abc")
        self.shutdown_reasons: list[str] = []

    async def _create(self, request):
        return object()

    async def shutdown(self, reason: str = "") -> None:
        self.shutdown_reasons.append(reason)


@pytest.fixture
def outbound_env(monkeypatch):
    monkeypatch.setenv("LIVEKIT_OUTBOUND_TRUNK_ID", "ST_test")
    monkeypatch.delenv("TELEGRAM_BOT_TOKEN", raising=False)
    monkeypatch.delenv("TELEGRAM_CHAT_ID", raising=False)
    monkeypatch.delenv("CAAL_OUTBOUND_RING_TIMEOUT_SECONDS", raising=False)
    monkeypatch.delenv("CAAL_OUTBOUND_MAX_DURATION_SECONDS", raising=False)


@pytest.mark.parametrize("category", ["machine", "uncertain", "unanswered"])
@pytest.mark.asyncio
async def test_a_reminder_call_says_nothing_to_a_nonhuman_answer(
    monkeypatch, outbound_env, two_reminders, category
) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders
    monkeypatch.setattr(voice_agent.agents, "AMD", _FakeAMDFactory(category))
    ctx = _FakeContext()
    session = _FakeSession()

    answered = await voice_agent.run_outbound_call(
        ctx, session, _config(reminder_id=selected), agent=None
    )

    assert answered is False
    assert session.said == []
    assert session.generated == []
    assert ctx.shutdown_reasons


@pytest.mark.asyncio
async def test_a_human_answer_opens_the_reminder_call_in_a_fixed_order(
    monkeypatch, outbound_env, two_reminders
) -> None:
    voice_agent = _load_voice_agent()
    selected, _other = two_reminders
    monkeypatch.setattr(voice_agent.agents, "AMD", _FakeAMDFactory("human"))
    ctx = _FakeContext()
    session = _FakeSession()
    config = _config(reminder_id=selected, user_id=ANA)

    assert await voice_agent.run_outbound_call(ctx, session, config, agent=None) is True
    assert session.said == []

    await voice_agent.deliver_outbound_opening(session, config)
    assert session.said == [
        voice_agent.REMINDER_CALL_GREETING,
        reminder_delivery.reminder_message(SELECTED_TITLE),
    ]
